version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env/development/database
      - .env/development/web
  redis:
    image: redis
    volumes:
      - redis_data:/data
  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data
  js:
    build: .
    tty: true
    command: "yarn build --watch"
    volumes:
      - .:/usr/src/app
  css:
    build: .
    tty: true
    command: "yarn build:css --watch"
    volumes:
      - .:/usr/src/app
  selenium_chrome:
    image:
      seleniarm/standalone-chromium:latest
    tty: true
    logging:
      driver: none
    ports:
      - "5900:5900"

volumes:
  db_data:
  redis_data:
